name: Claude light

on:
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * *'  # daily at 11:59pm


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install retry requests
          python3 -m pip install .
          python claude_light/test.py
